name: Update Selection GSheet

on:
  workflow_dispatch:
    inputs:
      pretalx_api_key:
        description: 'Optional: Enter a Pretalx api key to overwrite any preconfigured Github secret.'
      gsheet_client_secret_json:
        description: 'Optional: Enter a the contents of the client secret json provided for a Google API Service user to overwrite any preconfigured Github secret.'
      gsheet_spread_id:
        description: 'Optional: Enter a Google Spreadsheet id to overwrite any preconfigured Github secret.'
      gsheet_worksheet_name:
        description: 'Optional: Enter a Google Sheet name to overwrite any preconfigured Github secret.'
  schedule:
    - cron: '0 7 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      PRETALX_API_KEY: ${{ secrets.PRETALX_API_KEY }}
      GSHEET_CLIENT_SECRET_JSON: ${{ secrets.GSHEET_CLIENT_SECRET_JSON }}
      GSHEET_SPREAD_ID: ${{ vars.GSHEET_SPREAD_ID }}
      GSHEET_WORKSHEET_NAME: ${{ vars.GSHEET_WORKSHEET_NAME }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Environment
      uses: prefix-dev/setup-pixi@v0.5.1

    - name: Run Python Script
      run: pixi run gsheet
      shell: bash -el {0}